font_family Google Sans Code NF
font_size 14
cursor_shape beam
cursor_blink_interval -1
cursor_trail 100
remember_window_size no
initial_window_width 100c
initial_window_height 30c
hide_window_decorations yes
background_opacity 0.6
scrollback_lines 2000
enable_audio_bell no
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
copy_on_select clipboard
window_padding_width 12 20 12 20
scrollbar never
mouse_hide_wait 3.0
allow_remote_control yes
confirm_os_window_close 0
notify_on_cmd_finish unfocused
