# Overview settings
enable_hotarea=1
hotarea_size=10
ov_tab_mode=0
hotarea_corner=0
overviewgappi=10
overviewgappo=200

# Keyboard related
repeat_rate=60
repeat_delay=200
numlockon=0
xkb_rules_layout=us

# Touchpad settings
trackpad_natural_scrolling=1
disable_while_typing=1
swipe_min_threshold=5
mouse_natural_scrolling=0
accel_speed=1
drag_tile_to_tile=1
tap_and_drag=1
accel_profile=2
axis_scroll_factor=2.0
cursor_theme=Bibata-Modern-Ice
cursor_size=24
warpcursor=1
focus_on_activate=1
sloppyfocus=1

smartgaps=0
gappih=5
gappiv=5
gappoh=10
gappov=10
borderpx=4
border_radius=24
no_border_when_single=1
rootcolor=0x201b14ff
maximizescreencolor=0xffffffff
urgentcolor=0xad401fff
globalcolor=0xb153a7ff
scratchpadcolor=0x516c93ff
overlaycolor=0x14a57cff
focuscolor=0xffffffff
bordercolor=0x44444400
