# window rules
windowrule=title:Authentication required,isfloating:1
windowrule=title:Keybindings,isfloating:1
windowrule=title:Rename*,isfloating:1
windowrule=title:Compressing*,isfloating:1
windowrule=title:File Already Exists*,isfloating:1
windowrule=title:Extracting Files*,isfloating:1
windowrule=title:File Operation Progress*,isfloating:1
windowrule=title:Confirm to replace files*,isfloating:1
windowrule=appid:clipse,isfloating:1,width:600,height:800
windowrule=title:Mission Center,isfloating:1,width:1400,height:800
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture-in-Picture
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture in picture
windowrule=appid:localsend,offsety:90%,offsetx:98%,isfloating:1,focused_opacity:0.8,unfocused_opacity:0.5,allow_csd:0,width:400,height:740
windowrule=appid:org.kde.kdeconnect.app,offsety:90%,offsetx:98%,isfloating:1,focused_opacity:0.8,unfocused_opacity:0.5,allow_csd:0,width:400,height:740
windowrule=appid:org.kde.kdeconnect.daemon,offsety:90%,offsetx:98%,isfloating:1,focused_opacity:0.8,unfocused_opacity:0.5,allow_csd:0,width:500,height:280
windowrule=appid:nmtui,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:600
windowrule=appid:bluetui,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:600
windowrule=appid:cmus,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:600

# Layer rules
layerrule=noanim:1,noblur:1,layer_name:selection

