[mgr]
prepend_keymap = [
  { on = [ "<C-w>" ], run = 'shell --orphan "bash -c \"pkill swaybg; swaybg -i %s -m fill\""' },
  { on = [ "<C-s>" ], run = 'shell --orphan "bash -c \"bash ~/.config/Scripts/kde-send.sh %s\""' },
]
