decoration {
    rounding = 24
    dim_special = 0.4
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    blur {
        enabled = true
        popups = true
        passes = 4
        size = 6
        xray = false
        contrast = 1.6
        noise = 0.02
        brightness = 0.9
        vibrancy = 0.4
        vibrancy_darkness = 0.4
        ignore_opacity = true
        new_optimizations = true
    }

    shadow {
      enabled = false
    }
}

