layerrule = blur on, animation slide top, ignore_alpha 0, match:namespace waybar
layerrule = blur on, ignore_alpha 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace quickshell
layerrule = blur on, animation slide right, ignore_alpha 0, match:namespace notifications
layerrule = blur on, ignore_alpha 0, match:namespace logout_dialog

workspace = special:terminal, on-created-empty:[float; size 1000 600; move 880 440] alacritty, persistent:false

windowrule {
    name = Picture in picture Mode
    match:title = ^(Picture-in-Picture)$
    match:title = ^(Picture in picture)$
    float = on
    no_initial_focus = on
    move = 1420 790
    opacity = 1.0
    pin = on
    keep_aspect_ratio = on
    size = (monitor_w*0.25) (monitor_h*0.25)
}

windowrule {
    name = LocalSend
    match:class = localsend
    animation = slide right
    float = on
    no_initial_focus = off
    move = 1500 300
    opacity = 0.8
    pin = on
    size = (monitor_w*0.20) (monitor_h*0.70)
}

windowrule {
    name = KDE Connect
    match:class = org.kde.kdeconnect.app
    animation = slide right
    float = on
    no_initial_focus = off
    move = 1500 300
    opacity = 0.8
    pin = on
    size = (monitor_w*0.20) (monitor_h*0.70)
}

windowrule {
    name = KDE Connect Daemon
    match:class = org.kde.kdeconnect.daemon
    float = on
    no_initial_focus = on
    move = 1400 775
    opacity = 0.8
    pin = on
    size = (monitor_w*0.25) (monitor_h*0.25)
}
